export const config = {
    toolbar: {
        items: [
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "fontColor",
            "fontSize",
            "fontFamily",
            "subscript",
            "superscript",
            "alignment",
            "link",
            "bulletedList",
            "numberedList",
            "todoList",
            "|",
            "indent",
            "outdent",
            "horizontalLine",
            "pageBreak",
            "|",
            "codeBlock",
            "code",
            "imageUpload",
            "blockQuote",
            "insertTable",
            "mediaEmbed",
            "undo",
            "redo",
            "exportPdf",
        ],
    },
    codeSnippet_theme:'pojoaque',

    language: "en",
    image: {
        toolbar: ["imageTextAlternative", "imageStyle:full", "imageStyle:side"],
    },
    table: {
        contentToolbar: [
            "tableColumn",
            "tableRow",
            "mergeTableCells",
            "tableCellProperties",
            "tableProperties",
        ],
    },
    licenseKey: "",
};
